# Generated by Django 3.0.5 on 2020-08-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='img',
            new_name='image',
        ),
    ]
